### ISSUE TITLE
lv2lint FAIL: ui:resize not returned by 'extention_data'

### ISSUE THREAD

**Issue by SpotlightKid** [sjaehn/BShapr#16]
==> Beginne check()...
lv2lint 0.10.0
Copyright (c) 2016-2021 Hanspeter Portner (dev@open-music-kontrollers.ch)
Released under Artistic License 2.0 by Open Music Kontrollers
lilv_world_add_plugin(): warning: Duplicate plugin <https://www.jahnichen.de/plugins/lv2/BShapr>
lilv_world_add_plugin(): warning: ... found in file:///usr/lib/lv2/BShapr.lv2/
lilv_world_add_plugin(): warning: ... and      file:///home/chris/work/arch/aur/bshapr-git/src/bshapr/BShapr.lv2/ (ignored)
lilv_world_add_plugin(): warning: Duplicate plugin <https://www.jahnichen.de/plugins/lv2/BShapr-cv>
lilv_world_add_plugin(): warning: ... found in file:///usr/lib/lv2/BShapr.lv2/
lilv_world_add_plugin(): warning: ... and      file:///home/chris/work/arch/aur/bshapr-git/src/bshapr/BShapr.lv2/ (ignored)
<https://www.jahnichen.de/plugins/lv2/BShapr>
    [WARN]  Plugin Author Email
              foaf:mbox not found
              seeAlso: <http://lv2plug.in/ns/lv2core#project>
    [SKIP]  Plugin Version Minor
              lv2:minorVersion not found
              seeAlso: <http://lv2plug.in/ns/lv2core#minorVersion>
    [SKIP]  Plugin Version Micro
              lv2:microVersion not found
              seeAlso: <http://lv2plug.in/ns/lv2core#microVersion>
  <https://www.jahnichen.de/plugins/lv2/BShapr#gui>
    [FAIL]  UI Resize Interface
              ui:resize not returned by 'extention_data'
              seeAlso: <http://lv2plug.in/ns/extensions/ui#resize>

==> FEHLER: Ein Fehler geschah in check().
    Breche ab...

**Comment by sjaehn** [comment]
I just run it without `[FAIL] UI Resize Interface` error message (same lv2lint version). Hmmm....

You have two copies of the the plugin. I didn't add a version number yet (there are still only pre-releases). Are you sure that your latest version is in in file:///usr/lib/lv2/BShapr.lv2/ ?

Additional question: Which compiler version did you use? I heard of lot of problems with gcc < 8 and clang < 10.

**Comment by SpotlightKid** [comment]
The check is from the PKGBUILD for the `bshapr-git` AUR package:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bshapr-git#n40

It's run on the uninstalled bundle.

**Comment by SpotlightKid** [comment]
Compiler is gcc (GCC) 10.2.0 on Manjaro.

lv2lint 0.10.0 compiled from latest git a few days ago.

BShapr commit hash is 1a6c6f9.

**Comment by sjaehn** [comment]
I just committed the fix fe348b008c393e3d4e6f56c3db7f71930c7a99ff as the response of the issue #17 . Maybe this also caused the problems you described here. Please let me know if lv2lint works or not. And what about "real" lv2 hosts ?

**Comment by SpotlightKid** [comment]
Sorry, not, the lv2lint fail still persist. And if I install the plugin anyway and try to run it with jalv, I get:

```con
jalv.gtk https://www.jahnichen.de/plugins/lv2/BShapr
Plugin:       https://www.jahnichen.de/plugins/lv2/BShapr
UI:           https://www.jahnichen.de/plugins/lv2/BShapr#gui
JACK Name:    B.Shapr
Sample rate:  48000 Hz
Block length: 128 frames
MIDI buffers: 32768 bytes
Comm buffers: 1168000 bytes
Update rate:  30,0 Hz

[...]
suil error: Failed to find descriptor for <https://www.jahnichen.de/plugins/lv2/BShapr#gui> in /usr/lib/lv2/BShapr.lv2/BShaprGUI.so
```

and only the generic UI is shown.

Loading BShapr in Carla prints in the log:

    Could not find the requested GUI in the plugin UI library	

and also only the generic UI is available.

**Comment by sjaehn** [comment]
I'm afraid that this will need a bigger fix (I think C symbols). Do you see the same problems with the latest versions of the other B.* plugins? I didn't saw it on my test systems (not Manjaro).

Other point. The check() in the AUR package `lv2lint -t "Plugin Version *" -Mpack -I "${_name}.lv2/" "${_plugin_uri}"` indeed loads the plugin twice! First time via its include dir. Second time via its URI.

**Comment by sjaehn** [comment]
Or does this simple commit fix the problems: 1be39462f4d03714f7d8c428bcb9d4ced46e1df8 ?

**Comment by SpotlightKid** [comment]
> [...] loads the plugin twice! First time via its include dir. Second time via its URI.

Are you sure? The command doesn't run without a plugin URI and the lv2lint help texts suggests that `-I` only sets a search path:

    [-I] INCLUDE_DIR             use include directory to search for plugins (can be used multiple times)

> Or does this simple commit fix the problems: 1be3946 ?

Unfortunately not. Now I get `Failed to find descriptor for <https://www.jahnichen.de/plugins/lv2/BShapr#gui> in /usr/lib/lv2/BShapr.lv2/BShaprGUI.so` from lv2lint too.

**Comment by falkTX** [comment]
you are missing the symbol exports.
https://github.com/lv2/lv2/blob/master/lv2/core/lv2.h#L365

**Comment by sjaehn** [comment]
Thanks to mention @falkTX . I think this points in the right way. I know this statement to add `LV2_SYMBOL_EXPORT` to ALL functions loaded by the host. But even in the LV2 book I see it only in front of the `const LV2UI_Descriptor*`.  Why it works there (OK, its "native" C) ?

**Comment by falkTX** [comment]
That would be a mistake in the book then.
It works only if you compile it the regular way. if you say to the compiler to hide symbols (a requirement for plugins) then you in turn need to inform the compiler about which symbols you want exported, because by default there will be none.

**Comment by sjaehn** [comment]
I wonder why I've seen the same story  (`LV2_SYMBOL_EXPORT` only in front of the descriptor function but not in front of instantiate, cleanup, extension_data, ...) for ALL plugins I looked at (x42, omc, avtk, ycollet, ...).

BTW, I now made all functions static in b4674dda6d3f3d6757a98e0d03aaac35ef5cca32 . I really don't know why I didn't do this before.

**Comment by falkTX** [comment]
Because you really only need to export 1 symbol per plugin - the lv2[ui]_descriptor.
All the rest follows from there, instantiate, run, extensions etc etc

**Comment by sjaehn** [comment]
OK, then it makes sense for me. But it makes this error message even more surprising for me. As I exported the respective descriptors at https://github.com/sjaehn/BShapr/blob/master/src/BShapr.cpp#L1629 and at https://github.com/sjaehn/BShapr/blob/master/src/BShaprGUI.cpp#L1784 .

**Comment by sjaehn** [comment]
According to @SpotlightKid it compiles now. The AUR PKGBUILD (_vide supra_) check turns out to get in conflict between a previously installed (broken) version and the newly build version of this plugin and thus produces errors. But this is out of the scope of this repository. Therefore, I close this issue here.
